In [1]:
import numpy as np

In [2]:
# 1 Creating arrays with linspace
print("\n Creating evenly spaced numbers from 0 to 10:")
a1 = np.linspace(0, 10, 21)  # 21 numbers from 0 to 10
print(a1)



 Creating evenly spaced numbers from 0 to 10:
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [3]:
# 2 Creating arrays using arange (like a number line!)
print("\n Creating numbers from 0 to 5 with step 0.5:")
a2 = np.arange(0, 5, 0.5)
print(a2)



 Creating numbers from 0 to 5 with step 0.5:
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [4]:
import numpy as np
# 3 Let's define some vectors
v1 = np.array([1, -2.1, 3.2])
v2 = np.array([-2.3, 1, -1.8])

v1+v2

array([-1.3, -1.1,  1.4])

In [5]:
# Scalar and vector operations
print("\n Performing vector operation: 2*v1 + 3*v2")
print(2*v1 + 3*v2)



 Performing vector operation: 2*v1 + 3*v2
[-4.9 -1.2  1. ]


In [6]:
# Dot product of vectors (like projection)
print("\n Dot product of v1 and v2:")
print(np.dot(v1, v2))



 Dot product of v1 and v2:
-10.16


In [7]:
A = np.array([1,2,3])
B = np.array([3,4,5])

np.dot(A,B)

np.int64(26)

In [8]:
# Cross product (only for 3D vectors)
print("\n Cross product of v1 and v2:")
print(np.cross(v1, v2))



 Cross product of v1 and v2:
[ 0.58 -5.56 -3.83]


In [9]:
# Norm or Length of a vector
print("\n Length (magnitude) of vector v1:")
print(np.linalg.norm(v1))



 Length (magnitude) of vector v1:
3.956008088970497


In [10]:
#  Difference between numpy and math.sin
x = np.array([1,2,3,4,5,4,3,2,np.pi])
print("\n Using np.sin() on array:")
print(np.sin(x))

# Math module doesn't support arrays directly
import math
try:
    print(math.sin(x))
except TypeError as e:
    print("\n Error using math.sin() on array:", e)



 Using np.sin() on array:
[ 8.41470985e-01  9.09297427e-01  1.41120008e-01 -7.56802495e-01
 -9.58924275e-01 -7.56802495e-01  1.41120008e-01  9.09297427e-01
  1.22464680e-16]

 Error using math.sin() on array: only length-1 arrays can be converted to Python scalars


In [11]:
#  Now let's talk about MATRICES!

# Define two 3x3 matrices
A = np.array([[5,7,2],[-1,3,5],[0,1,7]])
B = np.array([[1,-2,2],[-1,3,0],[3,1,-7]])

print("\n Matrix A:\n", A)
print("\n Matrix B:\n", B)




 Matrix A:
 [[ 5  7  2]
 [-1  3  5]
 [ 0  1  7]]

 Matrix B:
 [[ 1 -2  2]
 [-1  3  0]
 [ 3  1 -7]]


In [12]:
# Linear combination of matrices
print("\n Linear combination: 3*A - 2*B")
print(3*A - 2*B)



 Linear combination: 3*A - 2*B
[[13 25  2]
 [-1  3 15]
 [-6  1 35]]


In [13]:
# Matrix properties
print("\n Type and shape of matrix A:")
print(type(A), A.shape)

# Transpose of matrix (flip rows and columns)
print("\n Transpose of A (A.T):")
print(A.T)



 Type and shape of matrix A:
<class 'numpy.ndarray'> (3, 3)

 Transpose of A (A.T):
[[ 5 -1  0]
 [ 7  3  1]
 [ 2  5  7]]


In [14]:
# Determinant of matrix A
print("\n Determinant of A:")
print(np.linalg.det(A))

# Trace of matrix A (sum of diagonal elements)
print("\n Trace of A:")
print(A.trace())



 Determinant of A:
126.99999999999999

 Trace of A:
15


In [15]:
# Element-wise multiplication
print("\n Element-wise multiplication A * B:")
print(A * B)

# Matrix multiplication (dot product of matrices)
print("\n Matrix multiplication A @ B or np.dot(A, B):")
print(A @ B)



 Element-wise multiplication A * B:
[[  5 -14   4]
 [  1   9   0]
 [  0   1 -49]]

 Matrix multiplication A @ B or np.dot(A, B):
[[  4  13  -4]
 [ 11  16 -37]
 [ 20  10 -49]]


In [16]:
# Inverse of matrix A
A1 = np.linalg.inv(A)
print("\n Inverse of A:")
print(A1)

# Check: A * A^(-1) = Identity matrix
print("\n A multiplied by its inverse:")
print(A @ A1)



 Inverse of A:
[[ 0.12598425 -0.37007874  0.22834646]
 [ 0.05511811  0.27559055 -0.21259843]
 [-0.00787402 -0.03937008  0.17322835]]

 A multiplied by its inverse:
[[ 1.00000000e+00  2.77555756e-17 -1.11022302e-16]
 [ 2.08166817e-17  1.00000000e+00 -2.77555756e-17]
 [ 6.93889390e-18  1.38777878e-17  1.00000000e+00]]


In [17]:
#  Creating a random 5x4 matrix with integers 0 to 100
import random
L = [random.randint(0, 101) for i in range(20)]
M = np.reshape(L, (5, 4))
print("\n Random 5x4 matrix M:")
print(M)



 Random 5x4 matrix M:
[[ 72   1  43  73]
 [ 27  12   7  42]
 [ 49  91  24  31]
 [ 42  74  38  47]
 [ 38  81  79 100]]


In [18]:
# Matrix dimensions
m, n = M.shape
print(f"\n Shape of M (rows x columns):, {m}, {n}")

# Accessing elements
print(f"\n Element at 4th row and 3rd column {M[3,2]}:")
print(M[3, 2])


 Shape of M (rows x columns):, 5, 4

 Element at 4th row and 3rd column 38:
38


In [19]:
#  Solving Linear System Ax = b
b = np.array([1, 2, 3])
x = np.linalg.solve(A, b)
print("\n Solving Ax = b using NumPy:")
print("b =", b)
print("x (solution) =", x)





 Solving Ax = b using NumPy:
b = [1 2 3]
x (solution) = [ 0.07086614 -0.03149606  0.43307087]


In [20]:
#  Check: A @ x should give b
print("\n🔍 Verifying A @ x == b:")
print(np.dot(A, x))



🔍 Verifying A @ x == b:
[1. 2. 3.]


In [21]:
#  Slicing in Matrices
print("\n🔍 Row 2 of A:", A[1])             # 2nd row
print("🔍 Element at (3,2):", A[2, 1])       # 3rd row, 2nd column
print("🔍 First two rows:\n", A[:2])         # First two rows



🔍 Row 2 of A: [-1  3  5]
🔍 Element at (3,2): 1
🔍 First two rows:
 [[ 5  7  2]
 [-1  3  5]]


In [22]:
#  Generate random 5x4 matrix of integers from 0 to 100
L = [random.randint(0, 100) for _ in range(20)]
M = np.reshape(L, (5, 4))
print("\n Random 5x4 matrix M:\n", M)
print("Shape of M:", M.shape)



 Random 5x4 matrix M:
 [[70 23 72  3]
 [ 9  2  0 45]
 [ 7 55  1 49]
 [20  3 49 28]
 [11 22 60 20]]
Shape of M: (5, 4)


In [23]:
def solve_2x2(A_manual, b_manual):
    a, b = A_manual[0]
    c, d = A_manual[1]
    det = a * d - b * c
    if det == 0:
        return "No unique solution"
    x = (d * b_manual[0] - b * b_manual[1]) / det
    y = (-c * b_manual[0] + a * b_manual[1]) / det
    return [x, y]

A_manual = [[3, 2], [1, -1]]
b_manual = [5, 1]
print("Manual A =", A_manual)
print("Manual b =", b_manual)
print("Manual Solution x =", solve_2x2(A_manual, b_manual))


Manual A = [[3, 2], [1, -1]]
Manual b = [5, 1]
Manual Solution x = [1.4, 0.4]


In [24]:
#  Now using NumPy for same system
A_np = np.array(A_manual)
b_np = np.array(b_manual)
print("\n NumPy Solution x =", np.linalg.solve(A_np, b_np))


 NumPy Solution x = [1.4 0.4]


# Cycle Stand

In [25]:
import numpy as np
b = np.array([4000,1000,6000,4000,1000,4000])
A = np.array([[.1,.2,.1,.2,.6,.5],[.2,.3,.25,.1,.1,.1],[.25,.13,.33,.26,.05,.1],[.15,.1,.17,.1,.05,.1],[.2,.17,.05,.14,.1,.1],[.1,.1,.1,.2,.1,.1]])
G = b.copy()

for i in range(100):
    G = A@G
print(G , sum(G))

[4845.33797402 3858.74535894 4016.41659834 2390.94291762 2649.46285932
 2239.09429176] 20000.00000000001


In [26]:
for i in range(len(A)):
    print(sum(A.T[i]))

1.0000000000000002
1.0
1.0
1.0
1.0
0.9999999999999999


In [27]:
eigvals, evecs = np.linalg.eig(A)
print(np.max(eigvals))
print(np.linalg.matrix_power(A, 100))

(0.9999999999999988+0j)
[[0.2422669  0.2422669  0.2422669  0.2422669  0.2422669  0.2422669 ]
 [0.19293727 0.19293727 0.19293727 0.19293727 0.19293727 0.19293727]
 [0.20082083 0.20082083 0.20082083 0.20082083 0.20082083 0.20082083]
 [0.11954715 0.11954715 0.11954715 0.11954715 0.11954715 0.11954715]
 [0.13247314 0.13247314 0.13247314 0.13247314 0.13247314 0.13247314]
 [0.11195471 0.11195471 0.11195471 0.11195471 0.11195471 0.11195471]]


# Gauss Seidel and Jacobbi

In [28]:
def gs(A, b, x, tol=1e-5, maxitr=50):
    A, b, x = np.array(A), np.array(b), np.array(x, dtype=float)
    if len(A) != len(b):
        return 'Not Good'

    n, k, error = len(A), 1, 1

    while k <= maxitr and error >= tol:
        new_x = x.copy()
        for i in range(n):
            new_x[i] = (b[i] - np.dot(A[i], x) + A[i, i] * x[i]) / A[i, i]
        error = np.linalg.norm(new_x - x)
        x, k = new_x.copy(), k + 1

    return new_x


In [29]:
def j(A, b, x, tol=1e-5, maxitr=50):
    A, b, x = np.array(A), np.array(b), np.array(x, dtype=float)
    if len(A) != len(b):
        return 'Not Good'

    n, k, error = len(A), 1, 1

    while k <= maxitr and error >= tol:
        old_x = x.copy()
        for i in range(n):
            x[i] = (b[i] - np.dot(A[i], x) + A[i, i] * x[i]) / A[i, i]
        error = np.linalg.norm(old_x - x)
        k += 1

    return x
